---
- name: Install Nginx
  hosts: web
  become: yes
  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx start
      service:
        name: nginx
        state: restarted
