---
- name: Update Ubuntu system packages
  hosts: control
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install passlib with pip
      ansible.builtin.pip:
        name: passlib
        state: present
