---
- name: Install and configure Samba server on Ubuntu
  hosts: web
  become: yes
  vars_prompt:
    - name: "samba_user_password"
      prompt: "Please enter the password for the Samba user"
      private: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  

    - name: Install Samba server
      apt:
        name: samba
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install passlib with pip
      ansible.builtin.pip:
        name: passlib
        state: present

    - name: Create shared directory
      file:
        path: /humans
        state: directory
        mode: '0777'

    - name: Create file
      lineinfile:
        path: /humans/1.txt
        line: "Samba Server"
        create: yes

    - name: Configure smb.conf for Samba shares
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {ansible_managed} #"
        block: |
          [shared]
          path = /humans
          browseable = yes
          read only = no
          guest ok = yes


    - name: Add Samba user
      user:
        name: user1
        password: "{{ samba_user_password | password_hash('sha512') }}"
        state: present

    - name: Set Samba password for user1
      expect:
        command: smbpasswd -a user1
        responses:
          (?i)New SMB password: samba_user_password "\n"
          (?i)Retype new SMB password: samba_user_password "\n"

    - name: Ensure Samba service restart
      service:
        name: smbd
        state: restarted

