---
- name: example using when
  hosts: localhost
  vars:
    install_nginx: true
  tasks:

    - name: nginx package install
      apt:
        name: nginx
        state: present
      when: install_nginx == true

    - name: apache2 package
      apt:
        name: apache2
        state: present
      when: install_nginx != true
